# Generated by Django 6.0 on 2025-12-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
