# Generated by Django 6.0 on 2025-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(choices=[('IT', 'Information Technology (IT)'), ('CSE', 'Computer Science & Engineering (CSE)'), ('CSD', 'Computer Science & Design (CSD)'), ('EEE', 'Electrical & Electronics Engineering (EEE)'), ('ECE', 'Electronics & Communication Engineering (ECE)'), ('MECH', 'Mechanical Engineering (MECH)'), ('CIV', 'Civil Engineering (CIV)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')]),
        ),
    ]
