# Generated by Django 6.0 on 2026-02-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentprofile_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(choices=[('IT', 'Information Technology (IT)'), ('CSE', 'Computer Science & Engineering (CSE)'), ('CSD', 'Computer Science & Design (CSD)'), ('EEE', 'Electrical & Electronics Engineering (EEE)'), ('ECE', 'Electronics & Communication Engineering (ECE)'), ('MECH', 'Mechanical Engineering (MECH)'), ('CIV', 'Civil Engineering (CIV)')], max_length=50)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
