# Generated by Django 6.0 on 2026-03-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studententry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEntry',
        ),
    ]
