# Generated by Django 6.0 on 2026-03-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_studententry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentregistry',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='studentregistry',
            name='roll_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
