# Generated by Django 6.0 on 2025-12-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='fee_supply',
        ),
        migrations.AddField(
            model_name='exam',
            name='fee_supply_large',
            field=models.DecimalField(decimal_places=2, default=1100.0, max_digits=10, verbose_name='Supply (>2 Subjects)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='fee_supply_small',
            field=models.DecimalField(decimal_places=2, default=600.0, max_digits=10, verbose_name='Supply (<=2 Subjects)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fee_regular',
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=10),
        ),
    ]
