# Generated by Django 6.0 on 2025-12-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_remove_exam_fee_supply_exam_fee_supply_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='exam_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SUPPLY', 'Supply')], max_length=50),
        ),
    ]
