# Generated by Django 6.0 on 2026-03-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_transaction_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
