# Generated by Django 6.0 on 2026-03-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_transaction_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_session_id',
        ),
    ]
