# Generated by Django 6.0 on 2026-03-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_remove_transaction_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
